is_end2end: true

network:
  _target_: models.filtr.FILTREnd2End
  num_queries: 250
  aux_loss: false

  backbone: ${baseline}

  # Encoder to refine features with position embeddings
  encoder:
    _target_: models.encoder.SimplePointTransformer
    embed_dim: 256
    depth: 3
    n_heads: 8

  # Transformer Decoder (Same as standard FILTR)
  decoder:
    _target_: models.pd_transformer.Transformer
    d_model: 256
    nhead: 8
    num_decoder_layers: 6
    dim_feedforward: 1024
    dropout: 0.1
    normalize_before: true
    return_intermediate_dec: false
    activation: relu

criterion:
  _target_: models.filtr.SetCriterion
  matcher:
    _target_: models.pd_matcher.HungarianMatcherPersistence
    cost_coord: 1.0
    cost_no_exist: 1.0
    use_exist_in_assignment: true
    use_cpu: true
  
  weight_dict:
    recon: 1.0
    existence: 1.0
    diag: 1.0

  losses:
    - "existence"
    - "recon"
    - "diag" 